# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('code', models.TextField(verbose_name='标识码')),
                ('remarks', models.TextField(verbose_name='备注信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
                ('belong', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Directory', verbose_name='商品归属库')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='微信昵称')),
                ('openid', models.CharField(default='default', max_length=100, verbose_name='用户标识')),
                ('gender', models.CharField(choices=[('男', 1), ('女', 2), ('未知', 0)], max_length=10, verbose_name='性别')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycode.Profile', verbose_name='拥有者'),
        ),
    ]
