# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cookie',
            field=models.CharField(default='', max_length=100, verbose_name='用户认证标识'),
        ),
    ]
