# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0002_profile_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, '男'), (2, '女'), (0, '未知')], max_length=10, verbose_name='性别'),
        ),
    ]
