# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0003_auto_20170531_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='freq',
            field=models.IntegerField(default=0, verbose_name='使用频率'),
        ),
        migrations.AddField(
            model_name='directory',
            name='status',
            field=models.CharField(choices=[(1, 'LIVE'), (0, 'DEAD')], default=1, max_length=10, verbose_name='仓库状态'),
        ),
    ]
