# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0004_auto_20170601_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
                ('type', models.CharField(choices=[('0', '建库'), ('1', '入库'), ('2', '出库')], max_length=10, verbose_name='日志类型')),
                ('dir', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Directory', verbose_name='所建库')),
                ('good', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Goods', verbose_name='操作商品')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Profile', verbose_name='日志所属人')),
            ],
        ),
    ]
