# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('0', '建库'), ('1', '入库'), ('2', '出库'), ('3', '删库'), ('4', '改库')], max_length=10, verbose_name='日志类型'),
        ),
    ]
