# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0006_auto_20170608_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Directory', verbose_name='所建库'),
        ),
        migrations.AlterField(
            model_name='log',
            name='good',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Goods', verbose_name='操作商品'),
        ),
    ]
